import { db } from "@workspace/db";
import {
  creditCardsTable,
  cashbackCategoriesTable,
  cardBenefitsTable,
} from "@workspace/db";
import { eq } from "drizzle-orm";

// Actual credit card product images sourced from issuer marketing CDNs.
// Cards without a known stable URL fall back to the gradient design in the UI.
const CARD_IMAGES: Record<string, string> = {
  // Chase
  "Chase Sapphire Preferred": "https://creditcards.chase.com/content/dam/jpmc-marketplace/card-art/sapphire_preferred_card.png",
  "Chase Sapphire Reserve": "https://creditcards.chase.com/content/dam/jpmc-marketplace/card-art/sapphire_reserve_card_Halo.png",
  "Chase Freedom Unlimited": "https://creditcards.chase.com/content/dam/jpmc-marketplace/card-art/freedom_unlimited_card_alt.png",
  "Chase Freedom Flex": "https://creditcards.chase.com/bcs/images.ctfassets.net/8qmz0ef3xzub/7KrVet3yXT2YntiE8PqwAe/8705c3a1b357e949f56bbab918e3cf11/freedom_flex_card_alt.webp",
  // American Express
  "American Express Gold Card": "https://icm.aexp-static.com/acquisition/card-art/NUS000000174_480x304_straight_withname.png",
  "American Express Platinum": "https://icm.aexp-static.com/acquisition/card-art/NUS000000363_480x304_straight_withname.png",
  "Amex Blue Cash Preferred": "https://icm.aexp-static.com/acquisition/card-art/NUS000000264_480x304_straight_withname.png",
  "Amex Blue Cash Everyday": "https://icm.aexp-static.com/acquisition/card-art/NUS000000305_480x304_straight_withname.png",
  // Capital One
  "Capital One Venture X": "https://ecm.capitalone.com/WCM/card/products/venturex-cg-static-card-1000x630-2.png",
  "Capital One Venture Rewards": "https://ecm.capitalone.com/WCM/card/products/venture_cardart_prim_323x203-1.png",
  "Capital One Savor Cash Rewards": "https://ecm.capitalone.com/WCM/card/products/new-savor-card-art/mobile.png",
  "Capital One SavorOne": "https://ecm.capitalone.com/WCM/card/products/savorone-2025-cardart.png",
  "Capital One Quicksilver": "https://ecm.capitalone.com/WCM/card/products/quicksilver_cardart.png",
  // Citi
  "Citi Double Cash": "https://aemapi.citi.com/content/dam/cfs/uspb/usmkt/cards/en/static/images/citi-double-cash-credit-card/citi-double-cash-credit-card_306x192.webp",
  "Citi Strata Premier": "https://aemapi.citi.com/content/dam/cfs/uspb/usmkt/cards/en/static/images/citi-strata-premier-credit-card/citi-strata-premier-credit-card_306x192.webp",
  "Citi Custom Cash": "https://aemapi.citi.com/content/dam/cfs/uspb/usmkt/cards/en/static/images/citi-custom-cash-credit-card/citi-custom-cash-credit-card_306x192.webp",
  // Bank of America
  "Bank of America Travel Rewards": "https://www.bankofamerica.com/content/images/ContextualSiteGraphics/CreditCardArt/en_US/Approved_PCM/8blm_trvsigcm_v_250x158.png",
  "Bank of America Premium Rewards": "https://www.bankofamerica.com/content/images/ContextualSiteGraphics/CreditCardArt/en_US/Approved_PCM/bofa_prmsigcm_255x158.png",
  // US Bank
  "US Bank Cash+": "https://www.usbank.com/content/dam/usbank/en/images/illustrations/card-art/credit-cards/photo-cash-plus-signature-lg.png",
  "US Bank Altitude Connect": "https://www.usbank.com/content/dam/usbank/en/images/illustrations/card-art/credit-cards/photo-altitude-connect-consumer.png",
  // Discover
  "Discover it Cash Back": "https://www.discover.com/content/dam/discover/en_us/credit-cards/card-acquisitions/grey-redesign/global/images/cardart/card-it.png",
  "Discover it Miles": "https://www.discover.com/content/dam/discover/en_us/credit-cards/card-acquisitions/grey-redesign/global/images/cardart/card-miles.png",
  // Wells Fargo
  "Wells Fargo Active Cash": "https://www.wellsfargo.com/assets/images/photography/product-photography/credit-cards/card_active_cash_visa_signature_600x337.png",
  "Wells Fargo Autograph": "https://www.wellsfargo.com/assets/images/photography/product-photography/credit-cards/card_autograph_visa_signature_600x337.png",
  // Bank of America
  "Bank of America Cash Rewards": "https://www.bankofamerica.com/content/images/ContextualSiteGraphics/CreditCardArt/en_US/Approved_PCM/8blm_cstmcrcm_v_250x158.png",
  // ── AIRLINE CO-BRANDED ─────────────────────────────────────────────
  "United Explorer Card": "https://creditcards.chase.com/content/dam/jpmc-marketplace/card-art/united_explorer_card.png",
  "United Quest Card": "https://creditcards.chase.com/content/dam/jpmc-marketplace/card-art/united_quest_card.png",
  "Southwest Rapid Rewards Plus": "https://creditcards.chase.com/content/dam/jpmc-marketplace/card-art/southwest_rr_plus_card.png",
  "Southwest Rapid Rewards Priority": "https://creditcards.chase.com/content/dam/jpmc-marketplace/card-art/southwest_rr_priority_card.png",
  "Delta SkyMiles Gold American Express": "https://icm.aexp-static.com/acquisition/card-art/NUS000000196_480x304_straight_withname.png",
  "Delta SkyMiles Platinum American Express": "https://icm.aexp-static.com/acquisition/card-art/NUS000000197_480x304_straight_withname.png",
  "Delta SkyMiles Reserve American Express": "https://icm.aexp-static.com/acquisition/card-art/NUS000000198_480x304_straight_withname.png",
  "Citi / AAdvantage Platinum Select": "https://aemapi.citi.com/content/dam/cfs/uspb/usmkt/cards/en/static/images/citi-aadvantage-platinum-select-credit-card/citi-aadvantage-platinum-select-credit-card_306x192.webp",
  "Alaska Airlines Visa Signature": "https://www.bankofamerica.com/content/images/ContextualSiteGraphics/CreditCardArt/en_US/Approved_PCM/blm_alasvscm_v_250x158.png",
  // ── HOTEL CO-BRANDED ───────────────────────────────────────────────
  "Marriott Bonvoy Boundless": "https://creditcards.chase.com/content/dam/jpmc-marketplace/card-art/marriott_bonvoy_boundless_card.png",
  "World of Hyatt Credit Card": "https://creditcards.chase.com/content/dam/jpmc-marketplace/card-art/world_of_hyatt_card.png",
  "IHG One Rewards Premier": "https://creditcards.chase.com/content/dam/jpmc-marketplace/card-art/ihg_one_rewards_premier_card.png",
  "Marriott Bonvoy Brilliant American Express": "https://icm.aexp-static.com/acquisition/card-art/NUS000000339_480x304_straight_withname.png",
  "Hilton Honors American Express Surpass": "https://icm.aexp-static.com/acquisition/card-art/NUS000000128_480x304_straight_withname.png",
  "Hilton Honors American Express Aspire": "https://icm.aexp-static.com/acquisition/card-art/NUS000000132_480x304_straight_withname.png",
  "Capital One Wyndham Rewards Earner+": "https://ecm.capitalone.com/WCM/card/products/wyndham-earner-plus-card-art.png",
};

const LOGO = {
  chase: "https://logo.clearbit.com/chase.com",
  citi: "https://logo.clearbit.com/citi.com",
  amex: "https://logo.clearbit.com/americanexpress.com",
  capitalOne: "https://logo.clearbit.com/capitalone.com",
  discover: "https://logo.clearbit.com/discover.com",
  wellsFargo: "https://logo.clearbit.com/wellsfargo.com",
  bankOfAmerica: "https://logo.clearbit.com/bankofamerica.com",
  usBank: "https://logo.clearbit.com/usbank.com",
  barclays: "https://logo.clearbit.com/barclays.com",
  apple: "https://logo.clearbit.com/apple.com",
  synchrony: "https://logo.clearbit.com/synchrony.com",
  pnc: "https://logo.clearbit.com/pnc.com",
  costco: "https://logo.clearbit.com/costco.com",
  amazon: "https://logo.clearbit.com/amazon.com",
  bilt: "https://logo.clearbit.com/biltrewards.com",
  robinhood: "https://logo.clearbit.com/robinhood.com",
  target: "https://logo.clearbit.com/target.com",
  walmart: "https://logo.clearbit.com/walmart.com",
  paypal: "https://logo.clearbit.com/paypal.com",
  td: "https://logo.clearbit.com/td.com",
  jetblue: "https://logo.clearbit.com/jetblue.com",
  hawaiian: "https://logo.clearbit.com/hawaiianairlines.com",
  aircanada: "https://logo.clearbit.com/aircanada.com",
  choice: "https://logo.clearbit.com/choicehotels.com",
};

const cards = [
  // ── CHASE ──────────────────────────────────────────────────────────────────
  {
    name: "Chase Sapphire Preferred",
    issuer: "Chase",
    network: "Visa" as const,
    annualFee: "95",
    signupBonus: "60,000 points after $4,000 spend in 3 months",
    signupBonusValue: "750",
    color: "linear-gradient(135deg, #1a2744, #2d4a8c)",
    logoUrl: LOGO.chase,
    categories: [
      { category: "Travel", rate: "0.05", isDefault: false },
      { category: "Dining", rate: "0.03", isDefault: false },
      { category: "Streaming", rate: "0.03", isDefault: false },
      { category: "Online Groceries", rate: "0.03", isDefault: false },
      { category: "Other", rate: "0.01", isDefault: true },
    ],
    benefits: [
      { name: "Trip Cancellation Insurance", description: "Up to $10,000 per trip for covered reasons", annualValue: "200" },
      { name: "Primary Rental Car Coverage", description: "Collision damage waiver when renting for personal use", annualValue: "150" },
      { name: "DashPass Membership", description: "Complimentary DoorDash DashPass subscription", annualValue: "96" },
      { name: "Travel Portal Bonus", description: "Points worth 25% more when redeemed through Chase Travel", annualValue: "100" },
      { name: "Trip Delay Reimbursement", description: "Up to $500 per ticket for delays over 12 hours", annualValue: "50" },
    ],
  },
  {
    name: "Chase Sapphire Reserve",
    issuer: "Chase",
    network: "Visa" as const,
    annualFee: "550",
    signupBonus: "60,000 points after $4,000 spend in 3 months",
    signupBonusValue: "900",
    color: "linear-gradient(135deg, #111827, #374151)",
    logoUrl: LOGO.chase,
    categories: [
      { category: "Travel", rate: "0.10", isDefault: false },
      { category: "Dining", rate: "0.03", isDefault: false },
      { category: "Groceries", rate: "0.03", isDefault: false },
      { category: "Other", rate: "0.01", isDefault: true },
    ],
    benefits: [
      { name: "$300 Annual Travel Credit", description: "Automatic credit for travel purchases each year", annualValue: "300" },
      { name: "Priority Pass Lounge Access", description: "Unlimited Priority Pass Select lounge access worldwide", annualValue: "429" },
      { name: "Global Entry / TSA PreCheck", description: "Up to $100 statement credit every 4 years", annualValue: "25" },
      { name: "DashPass Membership", description: "Complimentary DoorDash DashPass subscription", annualValue: "96" },
      { name: "Lyft Pink Membership", description: "Complimentary Lyft Pink All Access membership", annualValue: "199" },
    ],
  },
  {
    name: "Chase Freedom Unlimited",
    issuer: "Chase",
    network: "Visa" as const,
    annualFee: "0",
    signupBonus: "$200 bonus after $500 spend in 3 months",
    signupBonusValue: "200",
    color: "linear-gradient(135deg, #1e3a5f, #3b82f6)",
    logoUrl: LOGO.chase,
    categories: [
      { category: "Dining", rate: "0.03", isDefault: false },
      { category: "Drugstores", rate: "0.03", isDefault: false },
      { category: "Travel via Chase", rate: "0.05", isDefault: false },
      { category: "All Purchases", rate: "0.015", isDefault: true },
    ],
    benefits: [
      { name: "Purchase Protection", description: "Coverage for new purchases for 120 days against damage or theft, up to $500 per claim", annualValue: "75" },
      { name: "Extended Warranty", description: "Extends eligible US manufacturer warranties by an additional year", annualValue: "50" },
    ],
  },
  {
    name: "Chase Freedom Flex",
    issuer: "Chase",
    network: "Mastercard" as const,
    annualFee: "0",
    signupBonus: "$200 bonus after $500 spend in 3 months",
    signupBonusValue: "200",
    color: "linear-gradient(135deg, #1d4ed8, #2563eb)",
    logoUrl: LOGO.chase,
    categories: [
      { category: "Rotating Categories", rate: "0.05", isDefault: false },
      { category: "Dining", rate: "0.03", isDefault: false },
      { category: "Drugstores", rate: "0.03", isDefault: false },
      { category: "Travel via Chase", rate: "0.05", isDefault: false },
      { category: "Other", rate: "0.01", isDefault: true },
    ],
    benefits: [
      { name: "Cell Phone Protection", description: "Up to $800 per claim when you pay your monthly cell phone bill with the card", annualValue: "100" },
      { name: "Purchase Protection", description: "New purchases protected for 120 days against damage or theft", annualValue: "75" },
    ],
  },
  // ── CITI ───────────────────────────────────────────────────────────────────
  {
    name: "Citi Double Cash",
    issuer: "Citi",
    network: "Mastercard" as const,
    annualFee: "0",
    signupBonus: null,
    signupBonusValue: null,
    color: "linear-gradient(135deg, #1b4332, #2d6a4f)",
    logoUrl: LOGO.citi,
    categories: [
      { category: "All Purchases", rate: "0.02", isDefault: true },
    ],
    benefits: [
      { name: "Citi Entertainment", description: "Special access to purchase tickets to thousands of events", annualValue: "50" },
      { name: "Damage and Theft Protection", description: "Purchase protection for 120 days on new purchases", annualValue: "75" },
    ],
  },
  {
    name: "Citi Strata Premier",
    issuer: "Citi",
    network: "Mastercard" as const,
    annualFee: "95",
    signupBonus: "75,000 points after $4,000 spend in 3 months",
    signupBonusValue: "750",
    color: "linear-gradient(135deg, #003087, #0040bb)",
    logoUrl: LOGO.citi,
    categories: [
      { category: "Hotels", rate: "0.03", isDefault: false },
      { category: "Flights", rate: "0.03", isDefault: false },
      { category: "Restaurants", rate: "0.03", isDefault: false },
      { category: "Groceries", rate: "0.03", isDefault: false },
      { category: "Gas", rate: "0.03", isDefault: false },
      { category: "Other", rate: "0.01", isDefault: true },
    ],
    benefits: [
      { name: "$100 Hotel Credit", description: "$100 off a single hotel stay of $500+ booked via CitiTravel.com", annualValue: "100" },
      { name: "No Foreign Transaction Fees", description: "No fees on purchases made abroad", annualValue: "30" },
      { name: "Citi Entertainment Access", description: "Presale and preferred tickets for concerts, sports, dining, and more", annualValue: "50" },
    ],
  },
  {
    name: "Citi Custom Cash",
    issuer: "Citi",
    network: "Mastercard" as const,
    annualFee: "0",
    signupBonus: "$200 cash back after $1,500 spend in 6 months",
    signupBonusValue: "200",
    color: "linear-gradient(135deg, #0f3460, #16213e)",
    logoUrl: LOGO.citi,
    categories: [
      { category: "Top Eligible Category (up to $500/month)", rate: "0.05", isDefault: false },
      { category: "Other", rate: "0.01", isDefault: true },
    ],
    benefits: [
      { name: "Citi Entertainment", description: "Special access to purchase tickets to thousands of events", annualValue: "50" },
      { name: "No Foreign Transaction Fees", description: "No fees on international purchases", annualValue: "30" },
    ],
  },
  // ── AMERICAN EXPRESS ───────────────────────────────────────────────────────
  {
    name: "American Express Gold Card",
    issuer: "American Express",
    network: "Amex" as const,
    annualFee: "250",
    signupBonus: "60,000 Membership Rewards points after $6,000 spend in 6 months",
    signupBonusValue: "600",
    color: "linear-gradient(135deg, #78350f, #d97706)",
    logoUrl: LOGO.amex,
    categories: [
      { category: "Dining", rate: "0.04", isDefault: false },
      { category: "Restaurants", rate: "0.04", isDefault: false },
      { category: "Groceries", rate: "0.04", isDefault: false },
      { category: "Flights", rate: "0.03", isDefault: false },
      { category: "Other", rate: "0.01", isDefault: true },
    ],
    benefits: [
      { name: "$120 Dining Credit", description: "$10/month at Grubhub, The Cheesecake Factory, Goldbelly, and more", annualValue: "120" },
      { name: "$120 Uber Cash", description: "$10/month in Uber Cash for rides and Uber Eats", annualValue: "120" },
      { name: "Hotel Collection Access", description: "2x points at The Hotel Collection properties, $100 hotel credit", annualValue: "200" },
      { name: "Global Assist Hotline", description: "24/7 medical, legal, financial, and emergency assistance when traveling", annualValue: "100" },
    ],
  },
  {
    name: "American Express Platinum",
    issuer: "American Express",
    network: "Amex" as const,
    annualFee: "695",
    signupBonus: "80,000 Membership Rewards points after $8,000 spend in 6 months",
    signupBonusValue: "1600",
    color: "linear-gradient(135deg, #374151, #6b7280)",
    logoUrl: LOGO.amex,
    categories: [
      { category: "Flights (booked directly or via Amex Travel)", rate: "0.05", isDefault: false },
      { category: "Hotels (booked via Amex Travel)", rate: "0.05", isDefault: false },
      { category: "Other", rate: "0.01", isDefault: true },
    ],
    benefits: [
      { name: "$200 Annual Airline Fee Credit", description: "$200 statement credit per year for incidental airline fees", annualValue: "200" },
      { name: "$200 Hotel Credit", description: "$200 credit on prepaid Fine Hotels & Resorts or Hotel Collection bookings", annualValue: "200" },
      { name: "$240 Digital Entertainment Credit", description: "$20/month credit for eligible digital entertainment subscriptions", annualValue: "240" },
      { name: "Centurion Lounge Access", description: "Complimentary access to Amex Centurion Lounges worldwide", annualValue: "500" },
      { name: "Priority Pass Lounge Access", description: "Unlimited Priority Pass Select lounge access for you and 2 guests", annualValue: "429" },
      { name: "Global Entry / TSA PreCheck", description: "Up to $100 credit every 4.5 years for Global Entry or TSA PreCheck", annualValue: "25" },
      { name: "$189 CLEAR Plus Credit", description: "Annual credit for CLEAR Plus membership to move through security faster", annualValue: "189" },
      { name: "$300 Equinox Credit", description: "$25/month toward Equinox memberships and Equinox+ app", annualValue: "300" },
    ],
  },
  {
    name: "Amex Blue Cash Preferred",
    issuer: "American Express",
    network: "Amex" as const,
    annualFee: "95",
    signupBonus: "$250 statement credit after $3,000 spend in 6 months",
    signupBonusValue: "250",
    color: "linear-gradient(135deg, #1e40af, #3b82f6)",
    logoUrl: LOGO.amex,
    categories: [
      { category: "Groceries (US supermarkets, up to $6,000/yr)", rate: "0.06", isDefault: false },
      { category: "Streaming", rate: "0.06", isDefault: false },
      { category: "Transit", rate: "0.03", isDefault: false },
      { category: "Gas", rate: "0.03", isDefault: false },
      { category: "Other", rate: "0.01", isDefault: true },
    ],
    benefits: [
      { name: "$84 Disney Bundle Credit", description: "$7/month for Disney Bundle (Disney+, Hulu, ESPN+)", annualValue: "84" },
      { name: "Return Protection", description: "Up to $300 per item, $1,000 per year, if merchant won't accept return within 90 days", annualValue: "50" },
      { name: "Purchase Protection", description: "Coverage for new purchases for 90 days against theft or accidental damage", annualValue: "75" },
    ],
  },
  {
    name: "Amex Blue Cash Everyday",
    issuer: "American Express",
    network: "Amex" as const,
    annualFee: "0",
    signupBonus: "$200 statement credit after $2,000 spend in 6 months",
    signupBonusValue: "200",
    color: "linear-gradient(135deg, #0369a1, #0ea5e9)",
    logoUrl: LOGO.amex,
    categories: [
      { category: "Groceries (US supermarkets, up to $6,000/yr)", rate: "0.03", isDefault: false },
      { category: "Online Retail", rate: "0.03", isDefault: false },
      { category: "Gas", rate: "0.03", isDefault: false },
      { category: "Other", rate: "0.01", isDefault: true },
    ],
    benefits: [
      { name: "$84 Disney Bundle Credit", description: "$7/month for Disney Bundle (Disney+, Hulu, ESPN+)", annualValue: "84" },
      { name: "Car Rental Loss and Damage Insurance", description: "Protection when you use the card to reserve and pay for your rental", annualValue: "50" },
    ],
  },
  // ── CAPITAL ONE ────────────────────────────────────────────────────────────
  {
    name: "Capital One Venture X",
    issuer: "Capital One",
    network: "Visa" as const,
    annualFee: "395",
    signupBonus: "75,000 miles after $4,000 spend in 3 months",
    signupBonusValue: "750",
    color: "linear-gradient(135deg, #1e1b4b, #4338ca)",
    logoUrl: LOGO.capitalOne,
    categories: [
      { category: "Hotels (via Capital One Travel)", rate: "0.10", isDefault: false },
      { category: "Rental Cars (via Capital One Travel)", rate: "0.10", isDefault: false },
      { category: "Travel (via Capital One Travel)", rate: "0.05", isDefault: false },
      { category: "Other", rate: "0.02", isDefault: true },
    ],
    benefits: [
      { name: "$300 Travel Credit", description: "Annual credit for travel booked through Capital One Travel", annualValue: "300" },
      { name: "10,000 Anniversary Bonus Miles", description: "Bonus miles every account anniversary", annualValue: "100" },
      { name: "Priority Pass Lounge Access", description: "Unlimited Priority Pass lounge access for cardholder + 2 guests", annualValue: "429" },
      { name: "Global Entry / TSA PreCheck Credit", description: "Up to $100 credit for Global Entry or TSA PreCheck application fee", annualValue: "25" },
      { name: "Capital One Lounge Access", description: "Unlimited access to Capital One airport lounges", annualValue: "150" },
      { name: "Cell Phone Protection", description: "Up to $800 per claim, max 2 claims per year when you pay your cell phone bill with the card", annualValue: "100" },
    ],
  },
  {
    name: "Capital One Venture Rewards",
    issuer: "Capital One",
    network: "Visa" as const,
    annualFee: "95",
    signupBonus: "75,000 miles after $4,000 spend in 3 months",
    signupBonusValue: "750",
    color: "linear-gradient(135deg, #312e81, #4f46e5)",
    logoUrl: LOGO.capitalOne,
    categories: [
      { category: "Hotels (via Capital One Travel)", rate: "0.05", isDefault: false },
      { category: "Rental Cars (via Capital One Travel)", rate: "0.05", isDefault: false },
      { category: "All Purchases", rate: "0.02", isDefault: true },
    ],
    benefits: [
      { name: "Global Entry / TSA PreCheck Credit", description: "Up to $100 credit every 4 years", annualValue: "25" },
      { name: "Travel Accident Insurance", description: "Coverage when you pay for travel with the card", annualValue: "50" },
      { name: "No Foreign Transaction Fees", description: "No fees on international purchases", annualValue: "30" },
    ],
  },
  {
    name: "Capital One Savor Cash Rewards",
    issuer: "Capital One",
    network: "Mastercard" as const,
    annualFee: "95",
    signupBonus: "$300 cash bonus after $3,000 spend in 3 months",
    signupBonusValue: "300",
    color: "linear-gradient(135deg, #7c1d6f, #be185d)",
    logoUrl: LOGO.capitalOne,
    categories: [
      { category: "Dining", rate: "0.04", isDefault: false },
      { category: "Entertainment", rate: "0.04", isDefault: false },
      { category: "Streaming", rate: "0.04", isDefault: false },
      { category: "Groceries", rate: "0.03", isDefault: false },
      { category: "Other", rate: "0.01", isDefault: true },
    ],
    benefits: [
      { name: "Mastercard Concierge", description: "24/7 concierge service for travel, dining, and entertainment", annualValue: "50" },
      { name: "No Foreign Transaction Fees", description: "No fees on international purchases", annualValue: "30" },
      { name: "Extended Warranty", description: "Doubles the original warranty period up to one additional year", annualValue: "50" },
    ],
  },
  {
    name: "Capital One SavorOne",
    issuer: "Capital One",
    network: "Mastercard" as const,
    annualFee: "0",
    signupBonus: "$200 cash bonus after $500 spend in 3 months",
    signupBonusValue: "200",
    color: "linear-gradient(135deg, #9d174d, #ec4899)",
    logoUrl: LOGO.capitalOne,
    categories: [
      { category: "Dining", rate: "0.03", isDefault: false },
      { category: "Entertainment", rate: "0.03", isDefault: false },
      { category: "Groceries", rate: "0.03", isDefault: false },
      { category: "Streaming", rate: "0.03", isDefault: false },
      { category: "Other", rate: "0.01", isDefault: true },
    ],
    benefits: [
      { name: "No Foreign Transaction Fees", description: "No fees on international purchases", annualValue: "30" },
      { name: "Extended Warranty", description: "Doubles the original warranty period up to one additional year", annualValue: "50" },
    ],
  },
  {
    name: "Capital One Quicksilver",
    issuer: "Capital One",
    network: "Visa" as const,
    annualFee: "0",
    signupBonus: "$200 cash bonus after $500 spend in 3 months",
    signupBonusValue: "200",
    color: "linear-gradient(135deg, #374151, #9ca3af)",
    logoUrl: LOGO.capitalOne,
    categories: [
      { category: "All Purchases", rate: "0.015", isDefault: true },
    ],
    benefits: [
      { name: "No Foreign Transaction Fees", description: "No fees on international purchases", annualValue: "30" },
      { name: "Travel Accident Insurance", description: "Coverage when you purchase travel with the card", annualValue: "50" },
    ],
  },
  // ── DISCOVER ───────────────────────────────────────────────────────────────
  {
    name: "Discover it Cash Back",
    issuer: "Discover",
    network: "Discover" as const,
    annualFee: "0",
    signupBonus: "Cashback Match — Discover matches all cash back earned in the first year",
    signupBonusValue: "150",
    color: "linear-gradient(135deg, #7c2d12, #ea580c)",
    logoUrl: LOGO.discover,
    categories: [
      { category: "Rotating Categories", rate: "0.05", isDefault: false },
      { category: "Other", rate: "0.01", isDefault: true },
    ],
    benefits: [
      { name: "Cashback Match First Year", description: "Discover automatically matches all cash back earned at the end of your first year", annualValue: "150" },
      { name: "Free FICO Score", description: "Free FICO credit score monitoring on your statement", annualValue: "20" },
      { name: "No Foreign Transaction Fees", description: "No fee on purchases made outside the US", annualValue: "30" },
    ],
  },
  {
    name: "Discover it Miles",
    issuer: "Discover",
    network: "Discover" as const,
    annualFee: "0",
    signupBonus: "Miles Match — Discover matches all miles earned in the first year",
    signupBonusValue: "150",
    color: "linear-gradient(135deg, #92400e, #f59e0b)",
    logoUrl: LOGO.discover,
    categories: [
      { category: "All Purchases", rate: "0.015", isDefault: true },
    ],
    benefits: [
      { name: "Miles Match First Year", description: "Discover matches all miles earned at the end of your first year", annualValue: "150" },
      { name: "No Foreign Transaction Fees", description: "No fee on purchases made outside the US", annualValue: "30" },
      { name: "Free FICO Score", description: "Free FICO credit score monitoring", annualValue: "20" },
    ],
  },
  // ── WELLS FARGO ────────────────────────────────────────────────────────────
  {
    name: "Wells Fargo Active Cash",
    issuer: "Wells Fargo",
    network: "Visa" as const,
    annualFee: "0",
    signupBonus: "$200 cash rewards bonus after $500 spend in 3 months",
    signupBonusValue: "200",
    color: "linear-gradient(135deg, #7f1d1d, #dc2626)",
    logoUrl: LOGO.wellsFargo,
    categories: [
      { category: "All Purchases", rate: "0.02", isDefault: true },
    ],
    benefits: [
      { name: "Cell Phone Protection", description: "Up to $600 protection against damage or theft when you pay your monthly bill with the card", annualValue: "100" },
      { name: "Visa Signature Concierge", description: "24/7 concierge service for dining, travel, and entertainment assistance", annualValue: "50" },
    ],
  },
  {
    name: "Wells Fargo Autograph",
    issuer: "Wells Fargo",
    network: "Visa" as const,
    annualFee: "0",
    signupBonus: "20,000 bonus points after $1,000 spend in 3 months",
    signupBonusValue: "200",
    color: "linear-gradient(135deg, #991b1b, #ef4444)",
    logoUrl: LOGO.wellsFargo,
    categories: [
      { category: "Restaurants", rate: "0.03", isDefault: false },
      { category: "Travel", rate: "0.03", isDefault: false },
      { category: "Gas & EV Charging", rate: "0.03", isDefault: false },
      { category: "Transit", rate: "0.03", isDefault: false },
      { category: "Streaming", rate: "0.03", isDefault: false },
      { category: "Phone Plans", rate: "0.03", isDefault: false },
      { category: "Other", rate: "0.01", isDefault: true },
    ],
    benefits: [
      { name: "Cell Phone Protection", description: "Up to $600 per claim, max $1,200 per year against damage or theft", annualValue: "100" },
      { name: "Visa Signature Concierge", description: "24/7 concierge service for travel, dining, and entertainment", annualValue: "50" },
      { name: "Auto Rental Collision Damage Waiver", description: "Coverage when you rent a car and pay with the card", annualValue: "50" },
    ],
  },
  // ── BANK OF AMERICA ────────────────────────────────────────────────────────
  {
    name: "Bank of America Travel Rewards",
    issuer: "Bank of America",
    network: "Visa" as const,
    annualFee: "0",
    signupBonus: "25,000 online bonus points after $1,000 spend in 90 days",
    signupBonusValue: "250",
    color: "linear-gradient(135deg, #7c1d1d, #b91c1c)",
    logoUrl: LOGO.bankOfAmerica,
    categories: [
      { category: "All Purchases", rate: "0.015", isDefault: true },
    ],
    benefits: [
      { name: "No Annual Fee", description: "No annual fee, ever", annualValue: "0" },
      { name: "No Foreign Transaction Fees", description: "No fees on international purchases", annualValue: "30" },
      { name: "Preferred Rewards Bonus", description: "Up to 75% rewards bonus for Preferred Rewards members", annualValue: "75" },
    ],
  },
  {
    name: "Bank of America Premium Rewards",
    issuer: "Bank of America",
    network: "Visa" as const,
    annualFee: "95",
    signupBonus: "60,000 online bonus points after $4,000 spend in 90 days",
    signupBonusValue: "600",
    color: "linear-gradient(135deg, #5b21b6, #7c3aed)",
    logoUrl: LOGO.bankOfAmerica,
    categories: [
      { category: "Travel & Dining", rate: "0.02", isDefault: false },
      { category: "All Purchases", rate: "0.015", isDefault: true },
    ],
    benefits: [
      { name: "$100 Airline Incidental Credit", description: "Up to $100 per year for qualifying airline incidental purchases", annualValue: "100" },
      { name: "$100 TSA PreCheck / Global Entry Credit", description: "Statement credit for TSA PreCheck or Global Entry application fee", annualValue: "25" },
      { name: "No Foreign Transaction Fees", description: "No fees on international purchases", annualValue: "30" },
      { name: "Preferred Rewards Bonus", description: "Up to 75% rewards bonus for Preferred Rewards members", annualValue: "100" },
    ],
  },
  {
    name: "Bank of America Cash Rewards",
    issuer: "Bank of America",
    network: "Visa" as const,
    annualFee: "0",
    signupBonus: "$200 online cash rewards bonus after $1,000 spend in 90 days",
    signupBonusValue: "200",
    color: "linear-gradient(135deg, #6d1a36, #be123c)",
    logoUrl: LOGO.bankOfAmerica,
    categories: [
      { category: "Choice Category (gas, dining, travel, online shopping, etc.)", rate: "0.03", isDefault: false },
      { category: "Grocery Stores & Wholesale Clubs (up to $2,500/quarter)", rate: "0.02", isDefault: false },
      { category: "Other", rate: "0.01", isDefault: true },
    ],
    benefits: [
      { name: "Preferred Rewards Bonus", description: "Up to 75% rewards bonus for Preferred Rewards members", annualValue: "75" },
      { name: "Purchase Protection", description: "Coverage for new purchases against damage or theft", annualValue: "50" },
    ],
  },
  // ── US BANK ────────────────────────────────────────────────────────────────
  {
    name: "US Bank Cash+",
    issuer: "US Bank",
    network: "Visa" as const,
    annualFee: "0",
    signupBonus: "$200 rewards bonus after $1,000 spend in 120 days",
    signupBonusValue: "200",
    color: "linear-gradient(135deg, #1e3a5f, #0284c7)",
    logoUrl: LOGO.usBank,
    categories: [
      { category: "Two Chosen Categories (up to $2,000/quarter each)", rate: "0.05", isDefault: false },
      { category: "One Everyday Category", rate: "0.02", isDefault: false },
      { category: "Other", rate: "0.01", isDefault: true },
    ],
    benefits: [
      { name: "No Annual Fee", description: "No annual fee ever", annualValue: "0" },
      { name: "ExtendPay", description: "Pay large purchases over time in fixed monthly installments", annualValue: "30" },
    ],
  },
  {
    name: "US Bank Altitude Connect",
    issuer: "US Bank",
    network: "Visa" as const,
    annualFee: "95",
    signupBonus: "50,000 bonus points after $2,000 spend in 120 days",
    signupBonusValue: "500",
    color: "linear-gradient(135deg, #155e75, #0891b2)",
    logoUrl: LOGO.usBank,
    categories: [
      { category: "Travel (hotels, car rentals, vacation rentals)", rate: "0.04", isDefault: false },
      { category: "Gas & EV Charging", rate: "0.04", isDefault: false },
      { category: "Dining", rate: "0.02", isDefault: false },
      { category: "Streaming", rate: "0.02", isDefault: false },
      { category: "Other", rate: "0.01", isDefault: true },
    ],
    benefits: [
      { name: "TSA PreCheck / Global Entry Credit", description: "Up to $100 statement credit every 4 years", annualValue: "25" },
      { name: "No Foreign Transaction Fees", description: "No fees on international purchases", annualValue: "30" },
      { name: "Cell Phone Protection", description: "Up to $600 per claim against damage or theft when you pay your bill with the card", annualValue: "100" },
    ],
  },
  // ── PNC BANK ───────────────────────────────────────────────────────────────
  {
    name: "PNC Cash Unlimited",
    issuer: "PNC Bank",
    network: "Visa" as const,
    annualFee: "0",
    signupBonus: "$200 bonus after $1,000 spend in 3 months",
    signupBonusValue: "200",
    color: "linear-gradient(135deg, #1c3a5f, #f97316)",
    logoUrl: LOGO.pnc,
    categories: [
      { category: "All Purchases", rate: "0.015", isDefault: true },
    ],
    benefits: [
      { name: "No Annual Fee", description: "No annual fee ever", annualValue: "0" },
      { name: "Cell Phone Protection", description: "Up to $1,000 protection when you pay your bill with the card", annualValue: "100" },
    ],
  },
  // ── AIRLINE CO-BRANDED ─────────────────────────────────────────────────────
  {
    name: "United Explorer Card",
    issuer: "Chase / United Airlines",
    network: "Visa" as const,
    annualFee: "95",
    signupBonus: "60,000 bonus miles",
    signupBonusValue: "750",
    color: "linear-gradient(135deg, #002244, #0c2340)",
    logoUrl: LOGO.chase,
    categories: [
      { category: "United Purchases", rate: "0.02", isDefault: false },
      { category: "Dining", rate: "0.02", isDefault: false },
      { category: "Hotels", rate: "0.02", isDefault: false },
      { category: "Other", rate: "0.01", isDefault: true },
    ],
    benefits: [
      { name: "Free First Checked Bag", description: "Free first checked bag for you and a companion on United flights", annualValue: "140" },
      { name: "Priority Boarding", description: "Priority boarding on United-operated flights", annualValue: "30" },
      { name: "United Club Passes", description: "2 one-time United Club passes per year", annualValue: "118" },
      { name: "$100 Global Entry / TSA PreCheck Credit", description: "Statement credit every 4 years", annualValue: "25" },
      { name: "25% Back on In-Flight Purchases", description: "On food, beverages, and Wi-Fi on United-operated flights", annualValue: "30" },
    ],
  },
  {
    name: "United Quest Card",
    issuer: "Chase / United Airlines",
    network: "Visa" as const,
    annualFee: "250",
    signupBonus: "70,000 bonus miles + 500 PQP",
    signupBonusValue: "900",
    color: "linear-gradient(135deg, #1a3a5c, #002244)",
    logoUrl: LOGO.chase,
    categories: [
      { category: "United Purchases", rate: "0.03", isDefault: false },
      { category: "Dining", rate: "0.02", isDefault: false },
      { category: "Streaming", rate: "0.02", isDefault: false },
      { category: "Other", rate: "0.01", isDefault: true },
    ],
    benefits: [
      { name: "$200 United Travel Credit", description: "Annual statement credit for United purchases", annualValue: "200" },
      { name: "Free First & Second Checked Bags", description: "For primary cardmember and a companion", annualValue: "240" },
      { name: "5,000-Mile Anniversary Award Flight Credit", description: "When redeeming miles on United flights", annualValue: "75" },
      { name: "Priority Boarding & Lounge Passes", description: "2 United Club one-time passes per year", annualValue: "118" },
    ],
  },
  {
    name: "Southwest Rapid Rewards Plus",
    issuer: "Chase / Southwest Airlines",
    network: "Visa" as const,
    annualFee: "69",
    signupBonus: "50,000 points",
    signupBonusValue: "650",
    color: "linear-gradient(135deg, #304cb2, #1a2c6b)",
    logoUrl: LOGO.chase,
    categories: [
      { category: "Southwest Purchases", rate: "0.02", isDefault: false },
      { category: "Streaming", rate: "0.02", isDefault: false },
      { category: "Other", rate: "0.01", isDefault: true },
    ],
    benefits: [
      { name: "3,000 Anniversary Points", description: "Bonus points each cardmember anniversary", annualValue: "40" },
      { name: "2 EarlyBird Check-In", description: "Two EarlyBird Check-Ins per year", annualValue: "50" },
      { name: "25% Back on In-Flight Purchases", description: "On in-flight Wi-Fi, drinks, and messaging", annualValue: "20" },
    ],
  },
  {
    name: "Southwest Rapid Rewards Priority",
    issuer: "Chase / Southwest Airlines",
    network: "Visa" as const,
    annualFee: "149",
    signupBonus: "50,000 points",
    signupBonusValue: "650",
    color: "linear-gradient(135deg, #f9b510, #e07b00)",
    logoUrl: LOGO.chase,
    categories: [
      { category: "Southwest Purchases", rate: "0.03", isDefault: false },
      { category: "Hotels", rate: "0.02", isDefault: false },
      { category: "Rental Cars", rate: "0.02", isDefault: false },
      { category: "Streaming", rate: "0.02", isDefault: false },
      { category: "Other", rate: "0.01", isDefault: true },
    ],
    benefits: [
      { name: "$75 Southwest Travel Credit", description: "Annual statement credit toward Southwest purchases", annualValue: "75" },
      { name: "7,500 Anniversary Points", description: "Bonus points each year", annualValue: "100" },
      { name: "4 Upgraded Boardings per Year", description: "When available, upgrade to A1-A15 boarding position", annualValue: "120" },
      { name: "20% Back on In-Flight Purchases", description: "Drinks, messaging, and Wi-Fi", annualValue: "20" },
    ],
  },
  {
    name: "Delta SkyMiles Gold American Express",
    issuer: "American Express / Delta",
    network: "Amex" as const,
    annualFee: "150",
    signupBonus: "50,000 bonus miles",
    signupBonusValue: "600",
    color: "linear-gradient(135deg, #c5a368, #8b6f3c)",
    logoUrl: LOGO.amex,
    categories: [
      { category: "Delta Purchases", rate: "0.02", isDefault: false },
      { category: "Restaurants", rate: "0.02", isDefault: false },
      { category: "Groceries", rate: "0.02", isDefault: false },
      { category: "Other", rate: "0.01", isDefault: true },
    ],
    benefits: [
      { name: "Free First Checked Bag", description: "Free first checked bag on Delta flights for you and up to 8 companions", annualValue: "240" },
      { name: "$200 Delta Flight Credit", description: "After spending $10,000 in a calendar year", annualValue: "200" },
      { name: "Priority Boarding", description: "Main Cabin 1 priority boarding", annualValue: "30" },
      { name: "20% Back on In-Flight Purchases", description: "Statement credit on Delta in-flight purchases", annualValue: "30" },
    ],
  },
  {
    name: "Delta SkyMiles Platinum American Express",
    issuer: "American Express / Delta",
    network: "Amex" as const,
    annualFee: "350",
    signupBonus: "75,000 bonus miles",
    signupBonusValue: "900",
    color: "linear-gradient(135deg, #b8b8b8, #6e6e6e)",
    logoUrl: LOGO.amex,
    categories: [
      { category: "Delta Purchases", rate: "0.03", isDefault: false },
      { category: "Hotels", rate: "0.03", isDefault: false },
      { category: "Restaurants", rate: "0.02", isDefault: false },
      { category: "Groceries", rate: "0.02", isDefault: false },
      { category: "Other", rate: "0.01", isDefault: true },
    ],
    benefits: [
      { name: "Companion Certificate", description: "Annual round-trip Main Cabin companion certificate (taxes/fees apply)", annualValue: "400" },
      { name: "Free First Checked Bag", description: "On Delta flights for you and up to 8 companions", annualValue: "240" },
      { name: "$120 Resy Credit", description: "Up to $10/month at U.S. Resy restaurants", annualValue: "120" },
      { name: "$120 Rideshare Credit", description: "Up to $10/month for U.S. rideshare", annualValue: "120" },
      { name: "MQM Boost", description: "10,000 MQMs after $25K spend, again at $50K", annualValue: "150" },
    ],
  },
  {
    name: "Delta SkyMiles Reserve American Express",
    issuer: "American Express / Delta",
    network: "Amex" as const,
    annualFee: "650",
    signupBonus: "100,000 bonus miles",
    signupBonusValue: "1200",
    color: "linear-gradient(135deg, #1a1a1a, #404040)",
    logoUrl: LOGO.amex,
    categories: [
      { category: "Delta Purchases", rate: "0.03", isDefault: false },
      { category: "Other", rate: "0.0125", isDefault: true },
    ],
    benefits: [
      { name: "Delta Sky Club Access", description: "Complimentary access when flying Delta on the day of travel (15 visits/year)", annualValue: "650" },
      { name: "Centurion Lounge Access", description: "Access when flying Delta-operated flights booked with this card", annualValue: "300" },
      { name: "Companion Certificate (First/Comfort+/Main)", description: "Annual round-trip companion certificate", annualValue: "700" },
      { name: "$240 Resy Credit", description: "Up to $20/month at U.S. Resy restaurants", annualValue: "240" },
      { name: "$120 Rideshare Credit", description: "Up to $10/month for U.S. rideshare", annualValue: "120" },
      { name: "Free First Checked Bag", description: "On Delta flights", annualValue: "240" },
    ],
  },
  {
    name: "Citi / AAdvantage Platinum Select",
    issuer: "Citi / American Airlines",
    network: "Mastercard" as const,
    annualFee: "99",
    signupBonus: "50,000 AAdvantage miles",
    signupBonusValue: "650",
    color: "linear-gradient(135deg, #d6e9f7, #a3c8e8)",
    logoUrl: LOGO.citi,
    categories: [
      { category: "American Airlines Purchases", rate: "0.02", isDefault: false },
      { category: "Restaurants", rate: "0.02", isDefault: false },
      { category: "Gas", rate: "0.02", isDefault: false },
      { category: "Other", rate: "0.01", isDefault: true },
    ],
    benefits: [
      { name: "Free First Checked Bag", description: "Free first checked bag on domestic AA flights for you and up to 4 companions", annualValue: "200" },
      { name: "Preferred Boarding", description: "Group 5 preferred boarding on AA flights", annualValue: "30" },
      { name: "25% Back on In-Flight Purchases", description: "On AA in-flight food and beverages", annualValue: "30" },
      { name: "$125 American Airlines Flight Discount", description: "After $20,000 in spend in cardmember year", annualValue: "125" },
    ],
  },
  {
    name: "Alaska Airlines Visa Signature",
    issuer: "Bank of America / Alaska Airlines",
    network: "Visa" as const,
    annualFee: "95",
    signupBonus: "70,000 bonus miles + Companion Fare",
    signupBonusValue: "900",
    color: "linear-gradient(135deg, #01426a, #00558c)",
    logoUrl: LOGO.bankOfAmerica,
    categories: [
      { category: "Alaska Airlines Purchases", rate: "0.03", isDefault: false },
      { category: "Gas", rate: "0.02", isDefault: false },
      { category: "Groceries", rate: "0.02", isDefault: false },
      { category: "Other", rate: "0.01", isDefault: true },
    ],
    benefits: [
      { name: "Annual Companion Fare", description: "$99 fare ($23 in taxes/fees) when traveling with you on Alaska", annualValue: "350" },
      { name: "Free First Checked Bag", description: "For you and up to 6 companions on the same reservation", annualValue: "180" },
      { name: "20% Back on In-Flight Purchases", description: "Statement credit on Alaska in-flight purchases", annualValue: "20" },
      { name: "No Foreign Transaction Fees", description: "On purchases made abroad", annualValue: "30" },
    ],
  },
  // ── HOTEL CO-BRANDED ───────────────────────────────────────────────────────
  {
    name: "Marriott Bonvoy Boundless",
    issuer: "Chase / Marriott Bonvoy",
    network: "Visa" as const,
    annualFee: "95",
    signupBonus: "3 Free Night Awards",
    signupBonusValue: "1050",
    color: "linear-gradient(135deg, #4a2c5a, #2d1a39)",
    logoUrl: LOGO.chase,
    categories: [
      { category: "Marriott Bonvoy Hotels", rate: "0.06", isDefault: false },
      { category: "Gas", rate: "0.03", isDefault: false },
      { category: "Groceries", rate: "0.02", isDefault: false },
      { category: "Dining", rate: "0.02", isDefault: false },
      { category: "Other", rate: "0.02", isDefault: true },
    ],
    benefits: [
      { name: "Annual Free Night Award", description: "Each cardmember anniversary, valued up to 35,000 points", annualValue: "350" },
      { name: "Automatic Silver Elite Status", description: "Bonvoy Silver Elite each year", annualValue: "75" },
      { name: "15 Elite Night Credits", description: "Earn 15 Elite Night Credits each year toward higher status", annualValue: "120" },
      { name: "No Foreign Transaction Fees", description: "On purchases made abroad", annualValue: "30" },
    ],
  },
  {
    name: "World of Hyatt Credit Card",
    issuer: "Chase / Hyatt",
    network: "Visa" as const,
    annualFee: "95",
    signupBonus: "30,000 points + up to 30,000 more after $15K spend",
    signupBonusValue: "1100",
    color: "linear-gradient(135deg, #2d4373, #1a2a4d)",
    logoUrl: LOGO.chase,
    categories: [
      { category: "Hyatt Hotels", rate: "0.04", isDefault: false },
      { category: "Restaurants", rate: "0.02", isDefault: false },
      { category: "Airline Tickets", rate: "0.02", isDefault: false },
      { category: "Local Transit & Commuting", rate: "0.02", isDefault: false },
      { category: "Fitness Clubs & Gym Memberships", rate: "0.02", isDefault: false },
      { category: "Other", rate: "0.01", isDefault: true },
    ],
    benefits: [
      { name: "Free Night at Category 1-4 Hyatt", description: "Awarded each cardmember anniversary", annualValue: "300" },
      { name: "Automatic Discoverist Status", description: "Hyatt Discoverist status each year", annualValue: "100" },
      { name: "5 Elite Night Credits", description: "Plus 2 more for every $5K spent toward higher status", annualValue: "75" },
    ],
  },
  {
    name: "IHG One Rewards Premier",
    issuer: "Chase / IHG",
    network: "Mastercard" as const,
    annualFee: "99",
    signupBonus: "140,000 bonus points",
    signupBonusValue: "700",
    color: "linear-gradient(135deg, #c0392b, #7d2018)",
    logoUrl: LOGO.chase,
    categories: [
      { category: "IHG Hotels", rate: "0.10", isDefault: false },
      { category: "Travel", rate: "0.05", isDefault: false },
      { category: "Dining", rate: "0.05", isDefault: false },
      { category: "Gas", rate: "0.03", isDefault: false },
      { category: "Other", rate: "0.03", isDefault: true },
    ],
    benefits: [
      { name: "Anniversary Free Night", description: "Free night at any IHG hotel up to 40,000 points", annualValue: "200" },
      { name: "Automatic Platinum Elite Status", description: "IHG One Rewards Platinum Elite each year", annualValue: "120" },
      { name: "4th Night Free", description: "When redeeming points for an award stay of 4+ nights", annualValue: "150" },
      { name: "$50 United TravelBank Cash", description: "After spending $7K each year", annualValue: "50" },
      { name: "$100 Global Entry / TSA PreCheck Credit", description: "Every 4 years", annualValue: "25" },
    ],
  },
  {
    name: "Marriott Bonvoy Brilliant American Express",
    issuer: "American Express / Marriott Bonvoy",
    network: "Amex" as const,
    annualFee: "650",
    signupBonus: "95,000 bonus points",
    signupBonusValue: "950",
    color: "linear-gradient(135deg, #2c2c2c, #1a1a1a)",
    logoUrl: LOGO.amex,
    categories: [
      { category: "Marriott Bonvoy Hotels", rate: "0.06", isDefault: false },
      { category: "Restaurants", rate: "0.03", isDefault: false },
      { category: "Flights", rate: "0.03", isDefault: false },
      { category: "Other", rate: "0.02", isDefault: true },
    ],
    benefits: [
      { name: "Annual Free Night (85K points)", description: "Each cardmember anniversary, up to 85,000 Bonvoy points", annualValue: "750" },
      { name: "Automatic Platinum Elite Status", description: "Bonvoy Platinum Elite each year", annualValue: "300" },
      { name: "$300 Marriott Bonvoy Dining Credit", description: "Up to $25/month at participating Marriott restaurants", annualValue: "300" },
      { name: "$100 Property Credit", description: "On qualifying 2-night stays at The Ritz-Carlton or St. Regis", annualValue: "100" },
      { name: "Priority Pass Lounge Access", description: "Unlimited Priority Pass Select lounge access", annualValue: "429" },
      { name: "$100 Global Entry / TSA PreCheck Credit", description: "Every 4 years", annualValue: "25" },
    ],
  },
  {
    name: "Hilton Honors American Express Surpass",
    issuer: "American Express / Hilton",
    network: "Amex" as const,
    annualFee: "150",
    signupBonus: "130,000 bonus points",
    signupBonusValue: "650",
    color: "linear-gradient(135deg, #002b5b, #003e80)",
    logoUrl: LOGO.amex,
    categories: [
      { category: "Hilton Hotels", rate: "0.12", isDefault: false },
      { category: "Restaurants", rate: "0.06", isDefault: false },
      { category: "Groceries", rate: "0.06", isDefault: false },
      { category: "Gas", rate: "0.06", isDefault: false },
      { category: "Other", rate: "0.03", isDefault: true },
    ],
    benefits: [
      { name: "Free Night Reward", description: "After spending $15K in a calendar year", annualValue: "300" },
      { name: "Automatic Hilton Honors Gold Status", description: "Bonus points and complimentary breakfast at many properties", annualValue: "200" },
      { name: "Path to Diamond Status", description: "Spend $40K to earn Diamond status for the year", annualValue: "150" },
      { name: "10 Priority Pass Lounge Visits", description: "Per year for cardmember and one guest", annualValue: "100" },
    ],
  },
  {
    name: "Hilton Honors American Express Aspire",
    issuer: "American Express / Hilton",
    network: "Amex" as const,
    annualFee: "550",
    signupBonus: "150,000 bonus points",
    signupBonusValue: "850",
    color: "linear-gradient(135deg, #b89b6a, #7a663f)",
    logoUrl: LOGO.amex,
    categories: [
      { category: "Hilton Hotels", rate: "0.14", isDefault: false },
      { category: "Flights", rate: "0.07", isDefault: false },
      { category: "Rental Cars", rate: "0.07", isDefault: false },
      { category: "Restaurants", rate: "0.07", isDefault: false },
      { category: "Other", rate: "0.03", isDefault: true },
    ],
    benefits: [
      { name: "Annual Free Night Reward", description: "Use at virtually any Hilton property", annualValue: "1000" },
      { name: "Automatic Hilton Honors Diamond Status", description: "Top-tier elite status with breakfast, room upgrades, lounge access", annualValue: "500" },
      { name: "$400 Hilton Resort Credit", description: "$200 semi-annually at participating Hilton resorts", annualValue: "400" },
      { name: "$200 Flight Credit", description: "$50 quarterly toward eligible flight purchases", annualValue: "200" },
      { name: "$199 CLEAR Plus Credit", description: "Annual statement credit for CLEAR Plus", annualValue: "199" },
      { name: "Priority Pass Lounge Access", description: "Unlimited visits to 1,400+ lounges worldwide", annualValue: "429" },
    ],
  },
  {
    name: "Capital One Wyndham Rewards Earner+",
    issuer: "Capital One / Wyndham",
    network: "Visa" as const,
    annualFee: "75",
    signupBonus: "45,000 points",
    signupBonusValue: "450",
    color: "linear-gradient(135deg, #00407a, #002b54)",
    logoUrl: LOGO.capitalOne,
    categories: [
      { category: "Wyndham Hotels & Gas", rate: "0.08", isDefault: false },
      { category: "Dining", rate: "0.05", isDefault: false },
      { category: "Groceries", rate: "0.05", isDefault: false },
      { category: "Other", rate: "0.01", isDefault: true },
    ],
    benefits: [
      { name: "7,500 Anniversary Bonus Points", description: "Bonus points each cardmember year", annualValue: "75" },
      { name: "Automatic Wyndham Diamond Status", description: "Top-tier hotel elite status", annualValue: "150" },
      { name: "10% Off Award Redemptions", description: "Redeem stays for 10% fewer points", annualValue: "100" },
      { name: "No Foreign Transaction Fees", description: "On purchases made abroad", annualValue: "30" },
    ],
  },
  // ── APPLE ──────────────────────────────────────────────────────────────────
  {
    name: "Apple Card",
    issuer: "Goldman Sachs / Apple",
    network: "Mastercard" as const,
    annualFee: "0",
    signupBonus: null,
    signupBonusValue: null,
    color: "linear-gradient(135deg, #1f2937, #4b5563)",
    logoUrl: LOGO.apple,
    categories: [
      { category: "Apple Purchases", rate: "0.03", isDefault: false },
      { category: "Apple Pay Purchases", rate: "0.02", isDefault: false },
      { category: "Other", rate: "0.01", isDefault: true },
    ],
    benefits: [
      { name: "Daily Cash", description: "Cash back is deposited daily directly to your Apple Cash account", annualValue: "50" },
      { name: "No Annual Fee", description: "No annual fee, no late fees, no foreign transaction fees", annualValue: "30" },
      { name: "Financial Health Tools", description: "Built-in tools to track spending, set goals, and understand interest charges", annualValue: "20" },
    ],
  },
  // ── COSTCO / WAREHOUSE ─────────────────────────────────────────────
  {
    name: "Costco Anywhere Visa by Citi",
    issuer: "Citi / Costco",
    network: "Visa" as const,
    annualFee: "0",
    signupBonus: null,
    signupBonusValue: null,
    color: "linear-gradient(135deg, #005daa, #e31837)",
    logoUrl: LOGO.costco,
    categories: [
      { category: "Gas", rate: "0.04", isDefault: false },
      { category: "Restaurants", rate: "0.03", isDefault: false },
      { category: "Travel", rate: "0.03", isDefault: false },
      { category: "Costco", rate: "0.02", isDefault: false },
      { category: "Other", rate: "0.01", isDefault: true },
    ],
    benefits: [
      { name: "No Annual Fee with Costco Membership", description: "Free as long as your Costco membership is active", annualValue: "60" },
      { name: "No Foreign Transaction Fees", description: "On purchases made abroad", annualValue: "30" },
      { name: "Damage and Theft Protection", description: "Coverage on new purchases for 120 days", annualValue: "75" },
      { name: "Worldwide Car Rental Insurance", description: "Secondary coverage when you rent with the card", annualValue: "60" },
    ],
  },
  // ── BILT / RENT ────────────────────────────────────────────────────
  {
    name: "Bilt Mastercard",
    issuer: "Wells Fargo / Bilt",
    network: "Mastercard" as const,
    annualFee: "0",
    signupBonus: null,
    signupBonusValue: null,
    color: "linear-gradient(135deg, #111827, #4b5563)",
    logoUrl: LOGO.bilt,
    categories: [
      { category: "Travel", rate: "0.02", isDefault: false },
      { category: "Dining", rate: "0.03", isDefault: false },
      { category: "Rent", rate: "0.01", isDefault: false },
      { category: "Other", rate: "0.01", isDefault: true },
    ],
    benefits: [
      { name: "Pay Rent Without Fees", description: "Earn points on rent payments at no transaction cost (up to 100k pts/yr)", annualValue: "200" },
      { name: "Rent Day 2x Bonus", description: "Double points on non-rent purchases on the 1st of each month", annualValue: "150" },
      { name: "Cell Phone Protection", description: "Up to $800 per claim when paying your phone bill with the card", annualValue: "100" },
      { name: "Trip Delay & Cancellation Protection", description: "Coverage on travel booked with the card", annualValue: "75" },
    ],
  },
  // ── ROBINHOOD ──────────────────────────────────────────────────────
  {
    name: "Robinhood Gold Card",
    issuer: "Robinhood",
    network: "Visa" as const,
    annualFee: "0",
    signupBonus: null,
    signupBonusValue: null,
    color: "linear-gradient(135deg, #b8860b, #ffd700)",
    logoUrl: LOGO.robinhood,
    categories: [
      { category: "Other", rate: "0.03", isDefault: true },
    ],
    benefits: [
      { name: "3% Cashback Everywhere", description: "Flat 3% back on every purchase for Robinhood Gold members", annualValue: "300" },
      { name: "Cashback Auto-Invested", description: "Optionally route rewards into a brokerage or retirement account", annualValue: "50" },
      { name: "No Foreign Transaction Fees", description: "Use it abroad with no extra cost", annualValue: "30" },
      { name: "Metal Card", description: "Premium tungsten card construction", annualValue: "20" },
    ],
  },
  // ── CHASE BUSINESS ─────────────────────────────────────────────────
  {
    name: "Chase Ink Business Preferred",
    issuer: "Chase",
    network: "Visa" as const,
    annualFee: "95",
    signupBonus: "100,000 points after $8,000 spend in 3 months",
    signupBonusValue: "1250",
    color: "linear-gradient(135deg, #0b3d91, #1e6fd9)",
    logoUrl: LOGO.chase,
    categories: [
      { category: "Travel", rate: "0.03", isDefault: false },
      { category: "Shipping", rate: "0.03", isDefault: false },
      { category: "Internet/Cable/Phone", rate: "0.03", isDefault: false },
      { category: "Advertising", rate: "0.03", isDefault: false },
      { category: "Other", rate: "0.01", isDefault: true },
    ],
    benefits: [
      { name: "Cell Phone Protection", description: "Up to $1,000 per claim when paying business phone bills with the card", annualValue: "150" },
      { name: "Trip Cancellation/Interruption Insurance", description: "Up to $5,000 per trip", annualValue: "100" },
      { name: "Primary Auto Rental Coverage", description: "Primary collision damage waiver on business rentals", annualValue: "100" },
      { name: "25% Travel Bonus", description: "Points worth 25% more via Chase Travel portal", annualValue: "200" },
    ],
  },
  {
    name: "Chase Ink Business Cash",
    issuer: "Chase",
    network: "Visa" as const,
    annualFee: "0",
    signupBonus: "$350 after $3k spend, $400 more after $6k more in year 1",
    signupBonusValue: "750",
    color: "linear-gradient(135deg, #0d4a8a, #2d7dd2)",
    logoUrl: LOGO.chase,
    categories: [
      { category: "Office Supplies", rate: "0.05", isDefault: false },
      { category: "Internet/Cable/Phone", rate: "0.05", isDefault: false },
      { category: "Gas", rate: "0.02", isDefault: false },
      { category: "Restaurants", rate: "0.02", isDefault: false },
      { category: "Other", rate: "0.01", isDefault: true },
    ],
    benefits: [
      { name: "Free Employee Cards", description: "Add employee cards at no extra cost with spending limits", annualValue: "50" },
      { name: "Purchase Protection", description: "Up to $10,000 per claim on new business purchases", annualValue: "100" },
      { name: "Extended Warranty", description: "Adds an extra year to U.S. manufacturer warranties of 3 years or less", annualValue: "75" },
    ],
  },
  {
    name: "Chase Ink Business Unlimited",
    issuer: "Chase",
    network: "Visa" as const,
    annualFee: "0",
    signupBonus: "$750 cash back after $6,000 spend in 3 months",
    signupBonusValue: "750",
    color: "linear-gradient(135deg, #1f3a93, #5d8aef)",
    logoUrl: LOGO.chase,
    categories: [
      { category: "Other", rate: "0.015", isDefault: true },
    ],
    benefits: [
      { name: "Free Employee Cards", description: "Issue employee cards with custom spending limits", annualValue: "50" },
      { name: "Purchase Protection", description: "Up to $10,000 per claim on new business purchases", annualValue: "100" },
      { name: "Auto Rental Insurance", description: "Primary coverage on business rentals", annualValue: "75" },
    ],
  },
  // ── CHASE OTHER ────────────────────────────────────────────────────
  {
    name: "Chase Amazon Prime Visa",
    issuer: "Chase / Amazon",
    network: "Visa" as const,
    annualFee: "0",
    signupBonus: "$200 Amazon gift card upon approval",
    signupBonusValue: "200",
    color: "linear-gradient(135deg, #0a1f44, #ff9900)",
    logoUrl: LOGO.amazon,
    categories: [
      { category: "Amazon", rate: "0.05", isDefault: false },
      { category: "Whole Foods", rate: "0.05", isDefault: false },
      { category: "Restaurants", rate: "0.02", isDefault: false },
      { category: "Gas", rate: "0.02", isDefault: false },
      { category: "Travel", rate: "0.02", isDefault: false },
      { category: "Other", rate: "0.01", isDefault: true },
    ],
    benefits: [
      { name: "Requires Prime", description: "5% rate is for active Amazon Prime members only", annualValue: "0" },
      { name: "No Foreign Transaction Fees", description: "On purchases made abroad", annualValue: "30" },
      { name: "Purchase Protection", description: "120 days of damage and theft protection", annualValue: "75" },
    ],
  },
  {
    name: "United Gateway Card",
    issuer: "Chase / United Airlines",
    network: "Visa" as const,
    annualFee: "0",
    signupBonus: "20,000 bonus miles after $1,000 in 3 months",
    signupBonusValue: "240",
    color: "linear-gradient(135deg, #0a4d8c, #1e6fd9)",
    logoUrl: LOGO.chase,
    categories: [
      { category: "United Purchases", rate: "0.02", isDefault: false },
      { category: "Gas", rate: "0.02", isDefault: false },
      { category: "Transit", rate: "0.02", isDefault: false },
      { category: "Other", rate: "0.01", isDefault: true },
    ],
    benefits: [
      { name: "No Annual Fee", description: "United benefits at no yearly cost", annualValue: "0" },
      { name: "0% Intro APR for 12 Months", description: "On purchases for the first year", annualValue: "100" },
      { name: "Trip Cancellation Insurance", description: "Coverage when you book with the card", annualValue: "75" },
    ],
  },
  {
    name: "United Club Infinite Card",
    issuer: "Chase / United Airlines",
    network: "Visa" as const,
    annualFee: "525",
    signupBonus: "80,000 bonus miles after $5,000 in 3 months",
    signupBonusValue: "960",
    color: "linear-gradient(135deg, #001f3f, #003366)",
    logoUrl: LOGO.chase,
    categories: [
      { category: "United Purchases", rate: "0.04", isDefault: false },
      { category: "Dining", rate: "0.02", isDefault: false },
      { category: "Travel", rate: "0.02", isDefault: false },
      { category: "Other", rate: "0.01", isDefault: true },
    ],
    benefits: [
      { name: "United Club Membership", description: "Unlimited access to United Club lounges worldwide", annualValue: "750" },
      { name: "Free Checked Bags", description: "First and second checked bag free for cardholder + companion", annualValue: "320" },
      { name: "Global Entry / TSA PreCheck", description: "Up to $100 statement credit every 4 years", annualValue: "25" },
      { name: "Premier Access Travel Services", description: "Priority check-in, security, boarding, and baggage handling", annualValue: "100" },
    ],
  },
  {
    name: "Southwest Rapid Rewards Premier",
    issuer: "Chase / Southwest Airlines",
    network: "Visa" as const,
    annualFee: "99",
    signupBonus: "50,000 points after $1,000 in 3 months",
    signupBonusValue: "700",
    color: "linear-gradient(135deg, #d72027, #f9b612)",
    logoUrl: LOGO.chase,
    categories: [
      { category: "Southwest Purchases", rate: "0.03", isDefault: false },
      { category: "Hotels Via Southwest", rate: "0.02", isDefault: false },
      { category: "Local Transit", rate: "0.02", isDefault: false },
      { category: "Other", rate: "0.01", isDefault: true },
    ],
    benefits: [
      { name: "6,000 Anniversary Points", description: "Bonus points on each cardmember anniversary", annualValue: "84" },
      { name: "2 EarlyBird Check-Ins per Year", description: "Free EarlyBird Check-In on select flights", annualValue: "50" },
      { name: "No Foreign Transaction Fees", description: "On purchases made abroad", annualValue: "30" },
    ],
  },
  {
    name: "Marriott Bonvoy Bold",
    issuer: "Chase / Marriott",
    network: "Visa" as const,
    annualFee: "0",
    signupBonus: "30,000 points after $1,000 in 3 months",
    signupBonusValue: "240",
    color: "linear-gradient(135deg, #1c1c1c, #6d6d6d)",
    logoUrl: LOGO.chase,
    categories: [
      { category: "Marriott Stays", rate: "0.03", isDefault: false },
      { category: "Restaurants", rate: "0.02", isDefault: false },
      { category: "Other", rate: "0.01", isDefault: true },
    ],
    benefits: [
      { name: "15 Elite Night Credits", description: "Toward Marriott Bonvoy elite status each year", annualValue: "100" },
      { name: "Marriott Bonvoy Silver Status", description: "Automatic mid-tier elite status", annualValue: "50" },
      { name: "No Foreign Transaction Fees", description: "On purchases made abroad", annualValue: "30" },
    ],
  },
  {
    name: "IHG One Rewards Traveler",
    issuer: "Chase / IHG",
    network: "Mastercard" as const,
    annualFee: "0",
    signupBonus: "80,000 points after $2,000 in 3 months",
    signupBonusValue: "400",
    color: "linear-gradient(135deg, #cc0000, #ff7a00)",
    logoUrl: LOGO.chase,
    categories: [
      { category: "IHG Stays", rate: "0.05", isDefault: false },
      { category: "Gas", rate: "0.03", isDefault: false },
      { category: "Restaurants", rate: "0.03", isDefault: false },
      { category: "Other", rate: "0.02", isDefault: true },
    ],
    benefits: [
      { name: "4th Reward Night Free", description: "On award stays of 4+ nights", annualValue: "200" },
      { name: "IHG Silver Elite Status", description: "Earn higher level with $20k spend", annualValue: "50" },
      { name: "No Foreign Transaction Fees", description: "On purchases made abroad", annualValue: "30" },
    ],
  },
  // ── AMEX BUSINESS ──────────────────────────────────────────────────
  {
    name: "American Express Business Gold",
    issuer: "American Express",
    network: "Amex" as const,
    annualFee: "375",
    signupBonus: "70,000 points after $10,000 spend in 3 months",
    signupBonusValue: "1400",
    color: "linear-gradient(135deg, #b8860b, #ffd700)",
    logoUrl: LOGO.amex,
    categories: [
      { category: "Top 2 Categories", rate: "0.04", isDefault: false },
      { category: "Flights & Hotels", rate: "0.03", isDefault: false },
      { category: "Other", rate: "0.01", isDefault: true },
    ],
    benefits: [
      { name: "$240 Flexible Business Credit", description: "$20/month at FedEx, Grubhub, Office Supplies, etc.", annualValue: "240" },
      { name: "$155 Walmart+ Credit", description: "Monthly statement credit for Walmart+ membership", annualValue: "155" },
      { name: "25% Airline Bonus", description: "Up to 250k points back per year for flights via Amex Travel", annualValue: "200" },
    ],
  },
  {
    name: "American Express Business Platinum",
    issuer: "American Express",
    network: "Amex" as const,
    annualFee: "695",
    signupBonus: "150,000 points after $20,000 in 3 months",
    signupBonusValue: "3000",
    color: "linear-gradient(135deg, #c0c0c0, #f5f5f5)",
    logoUrl: LOGO.amex,
    categories: [
      { category: "Flights & Prepaid Hotels", rate: "0.05", isDefault: false },
      { category: "Large Purchases $5k+", rate: "0.015", isDefault: false },
      { category: "Other", rate: "0.01", isDefault: true },
    ],
    benefits: [
      { name: "$200 Airline Fee Credit", description: "Annual incidental airline fee credit", annualValue: "200" },
      { name: "$400 Dell Credit", description: "Up to $400/year in Dell Technologies statement credits", annualValue: "400" },
      { name: "$360 Indeed Credit", description: "Up to $90/quarter for Indeed posts", annualValue: "360" },
      { name: "$150 Adobe Credit", description: "Annual Adobe statement credit", annualValue: "150" },
      { name: "Centurion + Priority Pass", description: "Global lounge access for cardmember", annualValue: "500" },
      { name: "35% Airline Bonus", description: "Up to 1M points/year on Pay With Points flights", annualValue: "350" },
    ],
  },
  {
    name: "Marriott Bonvoy Bevy American Express",
    issuer: "American Express / Marriott",
    network: "Amex" as const,
    annualFee: "250",
    signupBonus: "85,000 points after $5,000 spend in 6 months",
    signupBonusValue: "680",
    color: "linear-gradient(135deg, #1a1a1a, #5e3a1d)",
    logoUrl: LOGO.amex,
    categories: [
      { category: "Marriott Stays", rate: "0.06", isDefault: false },
      { category: "Restaurants", rate: "0.04", isDefault: false },
      { category: "Groceries", rate: "0.04", isDefault: false },
      { category: "Other", rate: "0.02", isDefault: true },
    ],
    benefits: [
      { name: "Marriott Gold Elite Status", description: "Mid-tier hotel elite status", annualValue: "150" },
      { name: "15 Elite Night Credits", description: "Each calendar year toward elite status", annualValue: "100" },
      { name: "1 Free Night (50k pts)", description: "After spending $15,000 in a calendar year", annualValue: "300" },
    ],
  },
  {
    name: "Hilton Honors American Express",
    issuer: "American Express / Hilton",
    network: "Amex" as const,
    annualFee: "0",
    signupBonus: "70,000 points after $2,000 spend in 6 months",
    signupBonusValue: "350",
    color: "linear-gradient(135deg, #002663, #0066b2)",
    logoUrl: LOGO.amex,
    categories: [
      { category: "Hilton Stays", rate: "0.07", isDefault: false },
      { category: "Restaurants", rate: "0.05", isDefault: false },
      { category: "Gas", rate: "0.05", isDefault: false },
      { category: "Groceries", rate: "0.05", isDefault: false },
      { category: "Other", rate: "0.03", isDefault: true },
    ],
    benefits: [
      { name: "Hilton Honors Silver Status", description: "Automatic mid-tier hotel status", annualValue: "75" },
      { name: "Path to Gold with $20k Spend", description: "Spend $20,000 in a calendar year for Gold status", annualValue: "100" },
      { name: "No Annual Fee", description: "Earn Hilton points without a yearly cost", annualValue: "0" },
    ],
  },
  // ── CITI MORE ──────────────────────────────────────────────────────
  {
    name: "Citi Rewards+",
    issuer: "Citi",
    network: "Mastercard" as const,
    annualFee: "0",
    signupBonus: "20,000 points after $1,500 in 3 months",
    signupBonusValue: "200",
    color: "linear-gradient(135deg, #003b70, #0066b3)",
    logoUrl: LOGO.citi,
    categories: [
      { category: "Gas", rate: "0.02", isDefault: false },
      { category: "Groceries", rate: "0.02", isDefault: false },
      { category: "Other", rate: "0.01", isDefault: true },
    ],
    benefits: [
      { name: "Round-Up to Nearest 10 Points", description: "Every purchase is rounded up to the nearest 10 points", annualValue: "50" },
      { name: "10% Points Back", description: "On the first 100,000 points redeemed each year", annualValue: "100" },
      { name: "Citi Entertainment", description: "Special access to events and presales", annualValue: "50" },
    ],
  },
  {
    name: "Citi / AAdvantage MileUp",
    issuer: "Citi / American Airlines",
    network: "Mastercard" as const,
    annualFee: "0",
    signupBonus: "10,000 miles + $50 statement credit after $500 in 3 months",
    signupBonusValue: "200",
    color: "linear-gradient(135deg, #c8102e, #ce0e2d)",
    logoUrl: LOGO.citi,
    categories: [
      { category: "American Airlines", rate: "0.02", isDefault: false },
      { category: "Groceries", rate: "0.02", isDefault: false },
      { category: "Other", rate: "0.01", isDefault: true },
    ],
    benefits: [
      { name: "No Annual Fee", description: "Earn AAdvantage miles with no yearly cost", annualValue: "0" },
      { name: "25% Inflight Savings", description: "On food and beverages on American flights", annualValue: "30" },
    ],
  },
  {
    name: "Citi / AAdvantage Executive World Elite",
    issuer: "Citi / American Airlines",
    network: "Mastercard" as const,
    annualFee: "595",
    signupBonus: "70,000 miles after $7,000 in 3 months",
    signupBonusValue: "1050",
    color: "linear-gradient(135deg, #1a1a1a, #4d4d4d)",
    logoUrl: LOGO.citi,
    categories: [
      { category: "American Airlines", rate: "0.04", isDefault: false },
      { category: "Other", rate: "0.01", isDefault: true },
    ],
    benefits: [
      { name: "Admirals Club Membership", description: "Full access for cardholder + immediate family", annualValue: "850" },
      { name: "First Checked Bag Free", description: "For cardholder + 8 companions on AA flights", annualValue: "240" },
      { name: "Global Entry / TSA PreCheck", description: "Up to $120 credit every 4 years", annualValue: "30" },
      { name: "Priority Boarding & Check-In", description: "Group 4 boarding on American flights", annualValue: "75" },
    ],
  },
  // ── BARCLAYS ───────────────────────────────────────────────────────
  {
    name: "JetBlue Plus Card",
    issuer: "Barclays / JetBlue",
    network: "Mastercard" as const,
    annualFee: "99",
    signupBonus: "60,000 TrueBlue points after $1,000 in 90 days",
    signupBonusValue: "780",
    color: "linear-gradient(135deg, #003876, #00a3e0)",
    logoUrl: LOGO.jetblue,
    categories: [
      { category: "JetBlue Purchases", rate: "0.06", isDefault: false },
      { category: "Restaurants", rate: "0.02", isDefault: false },
      { category: "Groceries", rate: "0.02", isDefault: false },
      { category: "Other", rate: "0.01", isDefault: true },
    ],
    benefits: [
      { name: "Free First Checked Bag", description: "For cardholder + up to 3 companions on JetBlue flights", annualValue: "140" },
      { name: "5,000 Anniversary Points", description: "Each cardmember year", annualValue: "65" },
      { name: "Mosaic Status with $50k Spend", description: "Earn Mosaic for the rest of the year", annualValue: "200" },
      { name: "10% Points Rebate", description: "On every award flight redemption", annualValue: "100" },
    ],
  },
  {
    name: "Hawaiian Airlines World Elite Mastercard",
    issuer: "Barclays / Hawaiian Airlines",
    network: "Mastercard" as const,
    annualFee: "99",
    signupBonus: "70,000 miles after $2,000 in 90 days",
    signupBonusValue: "910",
    color: "linear-gradient(135deg, #6d2077, #c8102e)",
    logoUrl: LOGO.hawaiian,
    categories: [
      { category: "Hawaiian Airlines", rate: "0.03", isDefault: false },
      { category: "Gas", rate: "0.02", isDefault: false },
      { category: "Dining", rate: "0.02", isDefault: false },
      { category: "Groceries", rate: "0.02", isDefault: false },
      { category: "Other", rate: "0.01", isDefault: true },
    ],
    benefits: [
      { name: "Free First Checked Bag", description: "For cardholder on Hawaiian Airlines flights", annualValue: "120" },
      { name: "$100 Companion Discount", description: "Annual discount on roundtrip Hawaii flights", annualValue: "100" },
      { name: "50% Off One-Way Companion Ticket", description: "Inter-island companion discount", annualValue: "75" },
    ],
  },
  {
    name: "AAdvantage Aviator Red World Elite",
    issuer: "Barclays / American Airlines",
    network: "Mastercard" as const,
    annualFee: "99",
    signupBonus: "60,000 miles after one purchase + paying annual fee",
    signupBonusValue: "900",
    color: "linear-gradient(135deg, #b22234, #e53935)",
    logoUrl: LOGO.barclays,
    categories: [
      { category: "American Airlines", rate: "0.02", isDefault: false },
      { category: "Other", rate: "0.01", isDefault: true },
    ],
    benefits: [
      { name: "First Checked Bag Free", description: "For cardholder + 4 companions on AA domestic flights", annualValue: "120" },
      { name: "Preferred Boarding", description: "Group 5 boarding on American flights", annualValue: "50" },
      { name: "25% Inflight Savings", description: "On food and beverages and Wi-Fi on American flights", annualValue: "30" },
    ],
  },
  {
    name: "Aeroplan Card",
    issuer: "Chase / Air Canada",
    network: "Visa" as const,
    annualFee: "95",
    signupBonus: "75,000 Aeroplan points after $4,000 in 3 months",
    signupBonusValue: "1100",
    color: "linear-gradient(135deg, #c8102e, #1a1a1a)",
    logoUrl: LOGO.aircanada,
    categories: [
      { category: "Air Canada", rate: "0.03", isDefault: false },
      { category: "Dining", rate: "0.03", isDefault: false },
      { category: "Groceries", rate: "0.03", isDefault: false },
      { category: "Other", rate: "0.01", isDefault: true },
    ],
    benefits: [
      { name: "Free First Checked Bag", description: "On Air Canada flights for cardholder + up to 8 companions", annualValue: "240" },
      { name: "25K Aeroplan Status", description: "Pathway to Aeroplan elite status with spend", annualValue: "200" },
      { name: "No Foreign Transaction Fees", description: "On purchases made abroad", annualValue: "30" },
    ],
  },
  // ── US BANK MORE ───────────────────────────────────────────────────
  {
    name: "US Bank Altitude Reserve",
    issuer: "US Bank",
    network: "Visa" as const,
    annualFee: "400",
    signupBonus: "50,000 points after $4,500 in 3 months",
    signupBonusValue: "750",
    color: "linear-gradient(135deg, #0c3766, #2a6db1)",
    logoUrl: LOGO.usBank,
    categories: [
      { category: "Mobile Wallet", rate: "0.03", isDefault: false },
      { category: "Travel", rate: "0.03", isDefault: false },
      { category: "Other", rate: "0.01", isDefault: true },
    ],
    benefits: [
      { name: "$325 Travel & Dining Credit", description: "Annual statement credit on travel and restaurant purchases", annualValue: "325" },
      { name: "Priority Pass Lounge Access", description: "Up to 8 free visits per year", annualValue: "200" },
      { name: "Global Entry / TSA PreCheck", description: "Up to $100 credit every 4 years", annualValue: "25" },
      { name: "Cell Phone Protection", description: "Up to $600 per claim when you pay your bill with the card", annualValue: "75" },
    ],
  },
  {
    name: "US Bank Altitude Go",
    issuer: "US Bank",
    network: "Visa" as const,
    annualFee: "0",
    signupBonus: "20,000 points after $1,000 in 90 days",
    signupBonusValue: "200",
    color: "linear-gradient(135deg, #1a4480, #5b8def)",
    logoUrl: LOGO.usBank,
    categories: [
      { category: "Dining", rate: "0.04", isDefault: false },
      { category: "Streaming", rate: "0.02", isDefault: false },
      { category: "Groceries", rate: "0.02", isDefault: false },
      { category: "Gas", rate: "0.02", isDefault: false },
      { category: "Other", rate: "0.01", isDefault: true },
    ],
    benefits: [
      { name: "$15 Streaming Credit", description: "Annual statement credit for streaming services", annualValue: "15" },
      { name: "0% Intro APR for 12 Months", description: "On purchases for the first year", annualValue: "100" },
      { name: "Cell Phone Protection", description: "Up to $600 per claim with bill payment", annualValue: "75" },
    ],
  },
  // ── DISCOVER MORE ──────────────────────────────────────────────────
  {
    name: "Discover it Chrome",
    issuer: "Discover",
    network: "Discover" as const,
    annualFee: "0",
    signupBonus: "Cashback Match — all cash back doubled in year 1",
    signupBonusValue: "300",
    color: "linear-gradient(135deg, #4a4a4a, #c0c0c0)",
    logoUrl: LOGO.discover,
    categories: [
      { category: "Gas", rate: "0.02", isDefault: false },
      { category: "Restaurants", rate: "0.02", isDefault: false },
      { category: "Other", rate: "0.01", isDefault: true },
    ],
    benefits: [
      { name: "Cashback Match", description: "All rewards doubled at end of first year", annualValue: "200" },
      { name: "No Annual Fee", description: "No yearly fee, ever", annualValue: "0" },
      { name: "Free FICO Score", description: "Monitor your credit score for free", annualValue: "20" },
    ],
  },
  {
    name: "Discover it Student Cash Back",
    issuer: "Discover",
    network: "Discover" as const,
    annualFee: "0",
    signupBonus: "Cashback Match — all cash back doubled in year 1",
    signupBonusValue: "200",
    color: "linear-gradient(135deg, #ff6900, #ffb000)",
    logoUrl: LOGO.discover,
    categories: [
      { category: "Rotating Categories", rate: "0.05", isDefault: false },
      { category: "Other", rate: "0.01", isDefault: true },
    ],
    benefits: [
      { name: "Cashback Match", description: "All cash back doubled at end of first year", annualValue: "150" },
      { name: "Good Grades Reward", description: "$20 statement credit per year for GPA 3.0+", annualValue: "20" },
      { name: "No Annual Fee", description: "No yearly fee, ever", annualValue: "0" },
    ],
  },
  {
    name: "Discover it Secured",
    issuer: "Discover",
    network: "Discover" as const,
    annualFee: "0",
    signupBonus: "Cashback Match — all cash back doubled in year 1",
    signupBonusValue: "100",
    color: "linear-gradient(135deg, #2c3e50, #34495e)",
    logoUrl: LOGO.discover,
    categories: [
      { category: "Gas", rate: "0.02", isDefault: false },
      { category: "Restaurants", rate: "0.02", isDefault: false },
      { category: "Other", rate: "0.01", isDefault: true },
    ],
    benefits: [
      { name: "Build Credit Securely", description: "Refundable security deposit becomes credit limit", annualValue: "50" },
      { name: "Automatic Account Reviews", description: "Reviewed for upgrade to unsecured starting at 7 months", annualValue: "30" },
      { name: "Free FICO Score", description: "Monitor your credit score for free", annualValue: "20" },
    ],
  },
  // ── WELLS FARGO MORE ───────────────────────────────────────────────
  {
    name: "Wells Fargo Reflect",
    issuer: "Wells Fargo",
    network: "Visa" as const,
    annualFee: "0",
    signupBonus: null,
    signupBonusValue: null,
    color: "linear-gradient(135deg, #d71e28, #ffcd11)",
    logoUrl: LOGO.wellsFargo,
    categories: [
      { category: "Other", rate: "0.01", isDefault: true },
    ],
    benefits: [
      { name: "21-Month 0% Intro APR", description: "On purchases and balance transfers for 21 months", annualValue: "300" },
      { name: "Cell Phone Protection", description: "Up to $600 per claim with bill payment", annualValue: "75" },
      { name: "No Annual Fee", description: "No yearly fee", annualValue: "0" },
    ],
  },
  {
    name: "Choice Privileges Select Mastercard",
    issuer: "Wells Fargo / Choice Hotels",
    network: "Mastercard" as const,
    annualFee: "95",
    signupBonus: "60,000 points after $3,000 in 3 months",
    signupBonusValue: "360",
    color: "linear-gradient(135deg, #002677, #0078d4)",
    logoUrl: LOGO.choice,
    categories: [
      { category: "Choice Hotels", rate: "0.10", isDefault: false },
      { category: "Gas", rate: "0.05", isDefault: false },
      { category: "Groceries", rate: "0.05", isDefault: false },
      { category: "Other", rate: "0.02", isDefault: true },
    ],
    benefits: [
      { name: "Choice Platinum Elite Status", description: "Top hotel elite status while you have the card", annualValue: "150" },
      { name: "Annual 8,000-Point Bonus", description: "Each cardmember year", annualValue: "48" },
      { name: "$50 Annual Statement Credit", description: "On Choice Hotels stays each year", annualValue: "50" },
    ],
  },
  // ── PNC / TD ───────────────────────────────────────────────────────
  {
    name: "PNC Cash Rewards Visa",
    issuer: "PNC Bank",
    network: "Visa" as const,
    annualFee: "0",
    signupBonus: "$200 bonus after $1,000 in 3 months",
    signupBonusValue: "200",
    color: "linear-gradient(135deg, #ff6f00, #f57c00)",
    logoUrl: LOGO.pnc,
    categories: [
      { category: "Gas", rate: "0.04", isDefault: false },
      { category: "Restaurants", rate: "0.03", isDefault: false },
      { category: "Groceries", rate: "0.02", isDefault: false },
      { category: "Other", rate: "0.01", isDefault: true },
    ],
    benefits: [
      { name: "0% Intro APR for 15 Months", description: "On purchases and balance transfers", annualValue: "150" },
      { name: "No Annual Fee", description: "No yearly fee", annualValue: "0" },
    ],
  },
  {
    name: "TD Double Up Credit Card",
    issuer: "TD Bank",
    network: "Visa" as const,
    annualFee: "0",
    signupBonus: "$150 cash back after $1,000 in 90 days",
    signupBonusValue: "150",
    color: "linear-gradient(135deg, #008a3e, #45b07a)",
    logoUrl: LOGO.td,
    categories: [
      { category: "Other", rate: "0.02", isDefault: true },
    ],
    benefits: [
      { name: "2% Cash Back Everywhere", description: "Flat 2% back when redeemed into a TD account", annualValue: "200" },
      { name: "0% Intro APR for 15 Billing Cycles", description: "On balance transfers", annualValue: "150" },
      { name: "No Annual Fee", description: "No yearly fee", annualValue: "0" },
    ],
  },
  // ── RETAIL ─────────────────────────────────────────────────────────
  {
    name: "Target RedCard Credit Card",
    issuer: "TD Bank / Target",
    network: "Mastercard" as const,
    annualFee: "0",
    signupBonus: null,
    signupBonusValue: null,
    color: "linear-gradient(135deg, #cc0000, #ff1f1f)",
    logoUrl: LOGO.target,
    categories: [
      { category: "Target", rate: "0.05", isDefault: false },
      { category: "Other", rate: "0.01", isDefault: true },
    ],
    benefits: [
      { name: "5% Off at Target", description: "Every purchase at Target and Target.com", annualValue: "200" },
      { name: "Free Shipping at Target.com", description: "Most items ship free", annualValue: "60" },
      { name: "Extra 30 Days for Returns", description: "Beyond Target's normal return window", annualValue: "30" },
    ],
  },
  {
    name: "Capital One Walmart Rewards",
    issuer: "Capital One / Walmart",
    network: "Mastercard" as const,
    annualFee: "0",
    signupBonus: "5% off in-store with Walmart Pay for first 12 months",
    signupBonusValue: "150",
    color: "linear-gradient(135deg, #0071ce, #ffc220)",
    logoUrl: LOGO.walmart,
    categories: [
      { category: "Walmart.com", rate: "0.05", isDefault: false },
      { category: "Restaurants", rate: "0.02", isDefault: false },
      { category: "Travel", rate: "0.02", isDefault: false },
      { category: "Walmart In-Store", rate: "0.02", isDefault: false },
      { category: "Other", rate: "0.01", isDefault: true },
    ],
    benefits: [
      { name: "Special Financing on Big Purchases", description: "Available on qualifying Walmart purchases", annualValue: "100" },
      { name: "No Foreign Transaction Fees", description: "On purchases made abroad", annualValue: "30" },
    ],
  },
  {
    name: "PayPal Cashback Mastercard",
    issuer: "Synchrony / PayPal",
    network: "Mastercard" as const,
    annualFee: "0",
    signupBonus: null,
    signupBonusValue: null,
    color: "linear-gradient(135deg, #003087, #009cde)",
    logoUrl: LOGO.paypal,
    categories: [
      { category: "PayPal Purchases", rate: "0.03", isDefault: false },
      { category: "Other", rate: "0.02", isDefault: true },
    ],
    benefits: [
      { name: "No Annual Fee", description: "No yearly fee", annualValue: "0" },
      { name: "No Rewards Caps", description: "Earn unlimited cash back", annualValue: "50" },
      { name: "Cash Back to PayPal Balance", description: "Redeem rewards directly to your PayPal account", annualValue: "30" },
    ],
  },
];

export async function seedDatabase() {
  const existingCards = await db.select().from(creditCardsTable);
  const existingByName = new Map(existingCards.map((c) => [c.name, c]));

  // Backfill missing card images on existing cards (idempotent).
  for (const c of existingCards) {
    const url = CARD_IMAGES[c.name];
    if (url && c.cardImageUrl !== url) {
      await db
        .update(creditCardsTable)
        .set({ cardImageUrl: url })
        .where(eq(creditCardsTable.id, c.id));
    }
  }

  const missing = cards.filter((c) => !existingByName.has(c.name));
  if (missing.length === 0) {
    console.log(
      `Database already seeded (${existingCards.length} cards). No new cards to add.`,
    );
    return;
  }

  console.log(`Adding ${missing.length} new credit card(s)...`);

  for (const cardData of missing) {
    const [card] = await db
      .insert(creditCardsTable)
      .values({
        name: cardData.name,
        issuer: cardData.issuer,
        network: cardData.network,
        annualFee: cardData.annualFee,
        signupBonus: cardData.signupBonus,
        signupBonusValue: cardData.signupBonusValue,
        color: cardData.color,
        logoUrl: cardData.logoUrl,
        cardImageUrl: CARD_IMAGES[cardData.name] ?? null,
      })
      .returning();

    await db.insert(cashbackCategoriesTable).values(
      cardData.categories.map((c) => ({
        cardId: card.id,
        category: c.category,
        rate: c.rate,
        isDefault: c.isDefault,
      })),
    );

    await db.insert(cardBenefitsTable).values(
      cardData.benefits.map((b) => ({
        cardId: card.id,
        name: b.name,
        description: b.description,
        annualValue: b.annualValue ?? null,
      })),
    );
  }

  console.log(`Added ${missing.length} new credit cards successfully`);
}
